version: '3.8'

services:
  barcode-api:
    build: .
    container_name: barcode-api
    restart: unless-stopped
    environment:
      - FLASK_APP=wsgi:app
      - FLASK_ENV=production
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
