version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: barcode-app
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
